"""add links to step

Revision ID: 44c47bf0964d
Revises: ae51830d0cb5
Create Date: 2022-08-25 15:55:38.935015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c47bf0964d'
down_revision = 'ae51830d0cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Link',
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['task_id', 'step_number'], ['Step.id', 'Step.number'], name=op.f('fk_Link_task_id_Step')),
    sa.PrimaryKeyConstraint('task_id', 'step_number', name=op.f('pk_Link'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Link')
    # ### end Alembic commands ###
