"""empty message

Revision ID: ae51830d0cb5
Revises: 
Create Date: 2021-12-22 09:20:45.597322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae51830d0cb5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ProcessingTask",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("task_name", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("multi_step", sa.Boolean(), nullable=True),
        sa.Column("current_step", sa.Integer(), nullable=True),
        sa.Column("progress_value", sa.Float(), nullable=True),
        sa.Column("progress_start", sa.Float(), nullable=True),
        sa.Column("progress_target", sa.Float(), nullable=True),
        sa.Column("progress_unit", sa.String(length=100), nullable=True),
        sa.Column("task_status", sa.String(length=100), nullable=True),
        sa.Column("task_log", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ProcessingTask")),
    )
    op.create_table(
        "Step",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("step_id", sa.String(length=500), nullable=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("href", sa.String(length=500), nullable=True),
        sa.Column("ui_href", sa.String(length=500), nullable=True),
        sa.Column("cleared", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["ProcessingTask.id"], name=op.f("fk_Step_id_ProcessingTask")
        ),
        sa.PrimaryKeyConstraint("id", "number", name=op.f("pk_Step")),
    )
    op.create_table(
        "TaskData",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("key", sa.String(length=500), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["ProcessingTask.id"], name=op.f("fk_TaskData_id_ProcessingTask")
        ),
        sa.PrimaryKeyConstraint("id", "key", name=op.f("pk_TaskData")),
    )
    op.create_table(
        "TaskFile",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("security_tag", sa.String(length=64), nullable=False),
        sa.Column("storage_provider", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_storage_data", sa.Text(), nullable=False),
        sa.Column("file_type", sa.String(length=255), nullable=True),
        sa.Column("mimetype", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("task_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ProcessingTask.id"],
            name=op.f("fk_TaskFile_task_id_ProcessingTask"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TaskFile")),
    )
    with op.batch_alter_table("TaskFile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_TaskFile_file_name"), ["file_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("TaskFile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_TaskFile_file_name"))

    op.drop_table("TaskFile")
    op.drop_table("TaskData")
    op.drop_table("Step")
    op.drop_table("ProcessingTask")
    # ### end Alembic commands ###
