"""empty message

Revision ID: b889171b490f
Revises: a09e03db46a1
Create Date: 2023-11-09 12:33:37.697251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b889171b490f"
down_revision = "a09e03db46a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("DataBlob", schema=None) as batch_op:
        batch_op.execute("DELETE FROM DataBlob")
        batch_op.add_column(
            sa.Column("key", sa.String(length=500), nullable=False, primary_key=True)
        )
        batch_op.create_primary_key("pk_DataBlob", ["plugin_id", "key"])
        batch_op.drop_column("id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("DataBlob", schema=None) as batch_op:
        batch_op.execute("DELETE FROM DataBlob")
        batch_op.add_column(
            sa.Column("id", sa.INTEGER(), nullable=False, primary_key=True)
        )
        batch_op.create_primary_key("pk_DataBlob", ["id", "plugin_id"])
        batch_op.drop_column("key")

    # ### end Alembic commands ###
