"""empty message

Revision ID: e08125f1e6bc
Revises: 
Create Date: 2021-10-06 17:23:51.297527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08125f1e6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProcessingTask',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_name', sa.String(length=500), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('finished_status', sa.String(length=100), nullable=True),
    sa.Column('task_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ProcessingTask'))
    )
    with op.batch_alter_table('ProcessingTask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ProcessingTask_task_id'), ['task_id'], unique=False)

    op.create_table('TaskData',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['ProcessingTask.id'], name=op.f('fk_TaskData_task_id_ProcessingTask')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TaskData'))
    )
    op.create_table('TaskFile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('security_tag', sa.String(length=64), nullable=False),
    sa.Column('storage_provider', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_storage_data', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['ProcessingTask.id'], name=op.f('fk_TaskFile_task_id_ProcessingTask')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TaskFile'))
    )
    with op.batch_alter_table('TaskFile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_TaskFile_file_name'), ['file_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TaskFile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TaskFile_file_name'))

    op.drop_table('TaskFile')
    op.drop_table('TaskData')
    with op.batch_alter_table('ProcessingTask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ProcessingTask_task_id'))

    op.drop_table('ProcessingTask')
    # ### end Alembic commands ###
