"""add plugin to plugin interactions

Revision ID: ff55b6ebbbd7
Revises: b889171b490f
Create Date: 2024-02-21 15:33:09.410473

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff55b6ebbbd7"
down_revision = "b889171b490f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "TaskLink",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("href", sa.String(length=500), nullable=False),
        sa.Column("task_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ProcessingTask.id"],
            name=op.f("fk_TaskLink_task_id_ProcessingTask"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TaskLink")),
    )
    op.create_table(
        "TaskUpdateSubscription",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("webhook_href", sa.String(length=500), nullable=False),
        sa.Column("task_href", sa.String(length=500), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=True),
        sa.Column("task_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ProcessingTask.id"],
            name=op.f("fk_TaskUpdateSubscription_task_id_ProcessingTask"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TaskUpdateSubscription")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("TaskUpdateSubscription")
    op.drop_table("TaskLink")
    # ### end Alembic commands ###
