"""add plugin to plugin interactions

Revision ID: ff55b6ebbbd7
Revises: b889171b490f
Create Date: 2024-02-21 15:33:09.410473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff55b6ebbbd7'
down_revision = 'b889171b490f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaskLink',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('href', sa.String(length=500), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['ProcessingTask.id'], name=op.f('fk_TaskLink_task_id_ProcessingTask')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TaskLink'))
    )
    op.create_table('TaskUpdateSubscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('webhook_href', sa.String(length=500), nullable=False),
    sa.Column('task_href', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['ProcessingTask.id'], name=op.f('fk_TaskUpdateSubscription_task_id_ProcessingTask')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TaskUpdateSubscription'))
    )
    with op.batch_alter_table('ProcessingTask', schema=None) as batch_op:
        batch_op.alter_column('task_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('multi_step',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('current_step',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('progress_start',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('progress_target',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('progress_unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('Step', schema=None) as batch_op:
        batch_op.alter_column('step_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('href',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('ui_href',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('cleared',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('TaskFile', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TaskFile', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('Step', schema=None) as batch_op:
        batch_op.alter_column('cleared',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ui_href',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('href',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('step_id',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('ProcessingTask', schema=None) as batch_op:
        batch_op.alter_column('progress_unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('progress_target',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('progress_start',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('current_step',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('multi_step',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('task_name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    op.drop_table('TaskUpdateSubscription')
    op.drop_table('TaskLink')
    # ### end Alembic commands ###
