# Copyright 2023 QHAna plugin runner contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from marshmallow import post_load
import marshmallow as ma
from qhana_plugin_runner.api import EnumField
from qhana_plugin_runner.api.util import (
    FrontendFormBaseSchema,
    MaBaseSchema,
    FileUrl,
)

from .backend.initialization_enum import InitEnum
from .backend.method_enum import MethodEnum


class TaskResponseSchema(MaBaseSchema):
    name = ma.fields.String(required=True, allow_none=False, dump_only=True)
    task_id = ma.fields.String(required=True, allow_none=False, dump_only=True)
    task_result_url = ma.fields.Url(required=True, allow_none=False, dump_only=True)


class InputParameters:
    def __init__(
        self,
        entity_points_url: str,
        num_clusters: int,
        maxiter: int,
        init_enum: None,
        method_enum: None,
        visualize: bool = False,
    ):
        self.entity_points_url = entity_points_url
        self.num_clusters = num_clusters
        self.maxiter = maxiter
        self.init_enum = init_enum
        self.method_enum = method_enum
        self.visualize = visualize

    def __str__(self):
        variables = self.__dict__.copy()
        variables["ibmq_token"] = ""
        return str(variables)


class InputParametersSchema(FrontendFormBaseSchema):
    entity_points_url = FileUrl(
        required=True,
        allow_none=False,
        data_input_type="entity/vector",
        data_content_types=["application/json"],
        metadata={
            "label": "Entity Point URL",
            "description": "URL to a json file containing the points.",
            "input_type": "text",
        },
    )
    num_clusters = ma.fields.Integer(
        required=True,
        allow_none=False,
        metadata={
            "label": "Number of Clusters",
            "description": "Determines the number of clusters generated.",
            "input_type": "number",
        },
    )
    maxiter = ma.fields.Integer(
        required=True,
        allow_none=False,
        metadata={
            "label": "Max Iterations",
            "description": "The number of k medoids iterations..",
            "input_type": "number",
        },
    )
    init_enum = EnumField(
        InitEnum,
        required=True,
        allow_none=False,
        metadata={
            "label": "Initialization",
            "description": "Specify medoid initialization method:\n"
            "- random: selects n_clusters elements from the dataset."
            "- heuristic: picks the n_clusters points with the smallest sum distance to every other "
            "point.\n"
            "- k-medoids++: follows an approach based on k-means++_, and in general, gives initial "
            "medoids which are more separated than those generated by the other methods.\n"
            "- build: is a greedy initialization of the medoids used in the original PAM algorithm. "
            "Often ‘build’ is more efficient but slower than other initializations on big datasets and "
            "it is also very non-robust, if there are outliers in the dataset, use another "
            "initialization.\n",
            "input_type": "select",
        },
    )
    method_enum = EnumField(
        MethodEnum,
        required=True,
        allow_none=False,
        metadata={
            "label": "Method",
            "description": "Which algorithm to use. ‘alternate’ is faster while ‘pam’ is more accurate.",
            "input_type": "select",
        },
    )
    visualize = ma.fields.Boolean(
        required=False,
        allow_none=False,
        metadata={
            "label": "Visualize",
            "description": "Plot the clustered data.",
            "input_type": "checkbox",
        },
    )

    @post_load
    def make_input_params(self, data, **kwargs) -> InputParameters:
        return InputParameters(**data)
